travis:
  secure:
    BINSTAR_TOKEN: FqgUu+cMv2NgQK6i/40YOTu0G2CrsgiaGQG3Jw1Ykunvs2WMzhzkBV1hcNsc7pJUwUikOmb8nMcFeCEY/JzbMsvqICmYeRsZ4yYndib6MCdG2Ftp9KxxOAMSFx4PrcLyrNrpEuSjv8HPc7d7/S2YOKqK0DS4BSAQhNbhRugSyBQoE/AfhUr3dMq8l/rbAmPNie4D8VGv7CeT9800JvCb+Nl1lEEm73kc7+DHnRN9Esy9sRKRRYpDYu5dzUa9NpQNSqh9/bcwUI4HjlmGQqELN8U+0eF2nObSofDqLZOtqGiISllG93ZAR+BlRIz8AQnTFm+AuZRVHZkxg0bgbEN2HPF+qUXnGXxhuCJ06ezYEnI8LpwLtwDq2l967ZOh2YvgiTgcc0VnCMogXFSOQruzUjsSo6aJxosS0qa4yTYuEZOyuQ7V0fYtM+Dd3cCNeMysuVU9CGYS/i/nWcrrutfiuJbbOvbkbJr4OlD79EdSfPv34VYUV7TbzJP2D5KnAbl+tExOeR646SVOYW2wMteZ8d0VQufqJCgQ+TgTUk48megCbnGONOEE2vuybfker/UV/qw/mG6yAdJOVSskCS2IB8fADz6ac3IPOgEF3EnV+weWLQbWZr7CreT/5Sss7wxoG3ZxTjf5AwoBkdgx3Lw3CuVMlPFq503xsUJFFkCXsAE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
